owner: DatalinxAI
repo: status
user-agent: DatalinxAI

sites:
  - name: DataLinx App
    url: https://app.datalinx.ai
  - name: DataLinx API
    url: https://app.datalinx.ai/api/health
  - name: DataLinx Website
    url: https://www.datalinx.ai

status-website:
  baseUrl: /status
  logoUrl: https://www.datalinx.ai/logo.png
  name: DataLinx Status
  introTitle: "**DataLinx** service status"
  introMessage: This page shows real-time status and uptime for DataLinx services.
  navbar:
    - title: Status
      href: /
    - title: DataLinx
      href: https://www.datalinx.ai

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  graphs: "0 0 * * *"
  staticSite: "0 0 * * *"
  summary: "0 0 * * *"

i18n:
  activeIncidents: Active incidents
  allSystemsOperational: All systems operational
  incidentReport: Incident report for
  liveStatus: Live status
  overallUptime: Overall uptime
  pastIncidents: Past incidents
  responseTime: Response time
  uptime: Uptime
