owner: DatalinxAI
repo: status
user-agent: DatalinxAI

sites:
  - name: DataLinx App
    url: https://app.datalinx.ai
  - name: DataLinx Website
    url: https://datalinx.ai

status-website:
  baseUrl: /status
  logoUrl: https://www.datalinx.ai/logo.png
  name: DataLinx Status
  introTitle: "**DataLinx** service status"
  introMessage: This page shows real-time status and uptime for DataLinx services.
  navbar:
    - title: Status
      href: /status
    - title: DataLinx
      href: https://datalinx.ai

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  graphs: "0 0 * * *"
  staticSite: "0 0 * * *"
  summary: "0 0 * * *"

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All systems are operational
  incidentReport: "Incident #$NUMBER report →"
  liveStatus: Live Status
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average response
  pastIncidents: Past Incidents
  responseTime: Response time
  uptime: Uptime
  up: Up
  down: Down
  degraded: Degraded
  ms: ms
  loading: Loading
